import pyautogui as pg
import time

pg.hotkey('ctrl','winleft','d')
pg.hotkey('winleft')
pg.typewrite('chrome\n',0.5)
pg.typewrite('nike.com\n',0.5)
time.sleep(3.5)

pg.hotkey('tab')
time.sleep(0.1)
pg.hotkey('tab')
time.sleep(0.1)
pg.hotkey('tab')
time.sleep(0.1)
pg.hotkey('tab')
time.sleep(0.1)
pg.hotkey('tab')
time.sleep(0.1)
pg.hotkey('tab')
time.sleep(0.1)
pg.hotkey('tab')
time.sleep(0.1)
pg.hotkey('tab')
time.sleep(0.1)
pg.hotkey('tab')
time.sleep(0.1)
pg.hotkey('tab')
time.sleep(0.1)
pg.hotkey('tab')
time.sleep(0.1)
pg.hotkey('tab')
time.sleep(0.1)
pg.hotkey('tab')
time.sleep(0.1)
pg.hotkey('tab')
time.sleep(0.1)
pg.hotkey('tab')
time.sleep(0.1)
pg.hotkey('tab')
time.sleep(0.1)
pg.hotkey('tab')
time.sleep(0.1)
pg.hotkey('tab')
time.sleep(0.1)
pg.hotkey('tab')
time.sleep(0.1)
pg.typewrite('Jordan 1\n',0.2)




